version: "3.7"

services:
  reposistory:
    container_name: reposistory
    image: dockerrepository:latest
    build: ./Repository
    ports:
      - "4000:4000"
      - "4001:4001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="http://+"
    networks:
      - data
    extra_hosts:
      - "localhost:host-gateway"

  miner:
    container_name: miner
    image: dockerminer:latest
    build: ./Miner\MinerWrapper
    ports:
      - "5000:5000"
    networks:
      - data
    extra_hosts:
      - "localhost:host-gateway"

  serviceregistry:
    container_name: serviceregistry
    image: serviceregistry:latest
    build: ./ServiceRegistry
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="http://+"
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=4000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ServiceRegistry.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - data
    extra_hosts:
      - "localhost:host-gateway"

networks:
  data:
    driver: bridge
